import XCTest

extension TendUITests {
    @MainActor func testQuietHomeKeepsExtraCheckInAndMovesQuestionsToSettings() {
        launchFreshApp(window: "closed")
        onboard()
        XCTAssertEqual(app.tabBars.buttons.count, 3)
        XCTAssertFalse(app.tabBars.buttons["Q&A"].exists)
        XCTAssertEqual(app.buttons.matching(NSPredicate(format: "identifier BEGINSWITH %@", "home.scheduled.")).count, 0)
        XCTAssertTrue(app.staticTexts["Small moments of care count."].exists)
        XCTAssertTrue(app.buttons["home.checkIn"].isHittable)
        capture("quiet-home-window-closed")
        tap(app.buttons["home.checkIn"])
        XCTAssertTrue(app.buttons["ema.continue"].waitForExistence(timeout: 5))
        tap(app.buttons["ema.close"])
        tap(app.buttons["Save and close"])
        XCTAssertTrue(button(identifier: "home.checkIn", label: "Continue check-in").waitForExistence(timeout: 5))
        openQuestions()
        XCTAssertTrue(app.buttons["qa.question.0"].waitForExistence(timeout: 5))
        tap(app.buttons["qa.question.0"])
        XCTAssertTrue(labelContaining("one hour after each reminder").waitForExistence(timeout: 5))
        capture("questions-in-settings")
    }

    @MainActor func testCompletionReturnsTodayAndKeepsRemainingSuggestion() {
        launchFreshApp(window: "open")
        onboard()
        XCTAssertEqual(app.buttons.matching(NSPredicate(format: "identifier BEGINSWITH %@", "home.scheduled.")).count, 1)
        tap(app.buttons["home.scheduled.morning"])
        completeCheckIn(checkBackNavigation: false)
        tap(app.buttons["options.movement"])
        tap(app.buttons["practice.start"])
        tap(app.buttons["practice.finish"])
        tap(app.alerts.buttons["I completed this"])
        tap(app.buttons["feedback.postDistress.2"])
        tap(app.buttons["feedback.done"])
        XCTAssertTrue(app.buttons["practice.backToToday"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["practice.otherOption"].exists)
        capture("simple-completion")
        app.navigationBars.buttons.element(boundBy: 0).tap()
        XCTAssertTrue(app.buttons["options.done"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.buttons["options.otherOption"].exists)
        tap(app.buttons["options.done"])
        XCTAssertTrue(app.buttons["today.saved"].waitForExistence(timeout: 5))
        XCTAssertTrue(app.tabBars.buttons["Today"].isSelected)
        XCTAssertEqual(app.buttons.matching(NSPredicate(format: "identifier BEGINSWITH %@", "home.scheduled.")).count, 0)
        tap(app.buttons["today.saved"])
        XCTAssertTrue(app.buttons["saved.recommendation.mindful-breathing"].waitForExistence(timeout: 5))
        XCTAssertFalse(app.buttons["saved.recommendation.short-walk"].exists)
        capture("remaining-option-preserved")
        selectTab("Journey")
        assertTodayCounts(scheduled: 1, onDemand: 0)
    }
}
